language: go
matrix:
  include:
  - go: 1.15.x
    env: RELEASE_VERSION=true

# simple cross compile tool for go
before_install:
  - go get github.com/mitchellh/gox
  # - go get -t -v ./...

install:
  - # skip

script:
  - if [ "${RELEASE_VERSION}"  = "true" ]; then gox -os="linux darwin windows" -arch="amd64"
    -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

deploy:
  provider: releases
  api_key:
    secure: fLaGOUrGbhprGMAKnB2mh5HQS0D8MixYD/WQxiq12SA7nWmCX0GqNm9MdCOoou2irC4XKFACOqQkx0yYmKqgZ0LXYvPeqzs+F6SQjaYW8aglo/1xLm4O0LQWP2rs8AIdPGqbVCTMyj1hkJoGBAJA638TQbCPXqRLstMLesSCW3tITkhUMdkgW4zNgKCUVAg7YMD78c202nXUwdiKSdIJeaXOkOUJNe4ObkyC5TgHUSVZmC9hpMkWLtwIJcBelR1//Ym3a106IQyqlt9clmTh18/wDz8l5mvHUAO23W0Vzd6mJ7AiKQ+ZsKmK7IfshSVFG/pxBDtAKlcxikFW+0tpeSetGoto8YBvdK5HmyxeQaY2A5vpCHg6zKRKBNnWihMmq0AjgkB60PLmDc4pUj4LNy/Mn62lRA/A8RiO2CgXPUffRvwwIXmJoyLVUjBUp5z6c3VvjlnCZ/cgNczx5IRDGo2KRQrNQlFhMrMktZK6btq7R0XUaEMSn86UJa8+IvQ/GKLblA7JOXzDl26ooO0WNIHV0Bla3n841if5AuGnnYvPPSt7n38EjRLL1rkPpiaMKW66mCutfipuqc02+ZiZRgaeCO+05X5yQPCK9xXLdCjcPFo9MdXiSU4Xcu2k47pnNuTP4lOlmHHokKsee99IW/tmLx2d0cdFMg5FR7C3PKE=
  file:
    - "espoke_linux_amd64"
    - "espoke_darwin_amd64"
    - "espoke_windows_amd64.exe"
  skip_cleanup: true
  on:
    repo: criteo-forks/espoke
    tags: true
    condition: $RELEASE_VERSION = true
